Maddie/update api
fanout/php-grip pull request #3
Opened 2023-12-05 20:16 UTC by maddie-boby

tested locally

2023-12-08 18:55 UTC, sima-fastly reviewed
@maddie-boby I am unclear as what the purpose of this PR is , could you please include a ticket number or desc

2023-12-08 23:13 UTC, maddie-boby commented
@sima-fastly : I am updating the GRIP apis to work with Fastly's fanout. In particular, I'm adding support for using just a token as we do for authentication. @jkarneges can give more detail if necessary!

2023-12-11 07:03 UTC, harmony7 requested changes
This is mostly great! I have a few changes to suggest.

2023-12-11 07:03 UTC, harmony7 commented on src/Auth/JwtAuth.php
>       * @param array|string $claim_or_token
```suggestion
     * @param array $claim
```

2023-12-11 07:03 UTC, harmony7 commented on src/Auth/JwtAuth.php
> +        if( gettype( $claim ) === 'string' || $claim->iss !== $iss ) {
```suggestion
        if( $iss !== NULL && ( !property_exists( $claim,'iss' ) || $claim->iss !== $iss ) ) {
```

We only want to do this check if `$iss` was passed in.

`JWT::decode` is guaranteed to return an object if it didn't throw an exception.
However, if you try to read `->iss` on an object that doesn't have that field, it can raise `PHP Notice:  Undefined property`, so we make sure it's there.

2023-12-11 07:03 UTC, harmony7 commented on src/Engine/Publisher.php
> +            } else {
```suggestion
            } else if ( !empty( $key ) ) {
```

If both `$control_iss` and `$key` are empty, then we shouldn't set auth at all. This is the default behavior, and would be used with local Pushpin, etc.

2023-12-11 07:03 UTC, harmony7 commented on src/Utils/GripUriUtil.php
> +            unset ( $parsed_query[ 'verify-iss' ] );
```suggestion
            unset( $parsed_query[ 'verify-iss' ] );
```

Minor formatting

2023-12-12 04:23 UTC, harmony7 approved these changes

2023-12-12 04:23 UTC, merged